org: andrewreis
service: shonnen-arena-api
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x

  environment:
    ENVIRONMENT : ${env:ENVIRONMENT}

functions:
  http:
    handler: src/http.httpHandler
    events:
      - httpApi: "*"

  websocket:
    handler: src/ws/server.websocketHandler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: playerAction

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  excludeDevDependencies: true